# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
gem 'middleman', '4.2.1'
gem 'middleman-livereload'
gem 'middleman-minify-html'
gem 'middleman-syntax'
gem 'middleman-meta-tags'
gem 'middleman-robots'
gem 'middleman-search_engine_sitemap'
gem 'middleman-gh-pages'
gem 'slim'
gem 'sass'
gem 'coffee-script'
gem 'vital', path: '../'
